name: Code Scanning

on:
  push:
    branches:
      - '**' # Triggers on all branches

jobs:
  code-analysis:
    name: Run Code Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Code Scanning with Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif

      - name: Upload Code Scanning Results
        uses: github/codeql-action/upload-sarif
        with:
          sarif_file: results.sarif
